### ISSUE TITLE
Is coi a compile time or runtime di framework?

### ISSUE THREAD

**Issue by ibraheemdev** [Nashenas88/coi#34]
Does coi verify the dependency graph? If so, is this done at compile time, or run time?

**Comment by Nashenas88** [comment]
Verification of the dependency graph can done at runtime after construction of the container when the `debug` feature is turned on for the crate and you call `analyzer` on the container.  By default, no verification is done and resolution can fail quite some time after the container is built if the offending nodes are not requested for a while. See https://docs.rs/coi/0.10.0/coi/#debugging and https://docs.rs/coi/0.10.0/coi/struct.Container.html#method.analyze. If you feel the documentation isn't clear, please file a documentation bug.
