### ISSUE TITLE
Possibly redundant code in the readme?

### ISSUE THREAD

**Issue by MxFr** [Nashenas88/coi#5]
Is this code in the README.md redundant? 

```
       let mut container = container!{
            trait1 => Impl1,
            trait2 => Impl2.scoped,
            struct => JustAStruct.singleton
        };
        let mut container = ContainerBuilder::new()
            .register("trait1", Impl1Provider)
            .register_as("trait2", Registration::Scoped(Impl2Provider))
            .register_as("struct", Registration::Singleton(JustAStructProvider))
            .build();
```

I've looked at the test cases and they only contain the the first way to construct the container.

Since the code in the readme might be the first impression of coi, I think this should be adressed.

**Comment by tobni** [comment]
It's showcasing two ways of expressing the same thing. It is hardly redundant in the sense of showing what apis are available.

That said, maybe a comment is in order.

**Comment by Nashenas88** [comment]
That might have been an issue from a merge conflict. The latter is what the former produces, and was what the documentation used to have. I'll fix that. Thanks for reporting the issue!
